from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
import os


def create_report(name, prediction, risk):

    if not os.path.exists("reports"):
        os.makedirs("reports")

    filename = f"reports/{name}_report.pdf"

    c = canvas.Canvas(
        filename,
        pagesize=letter
    )

    width, height = letter

    c.setFont(
        "Helvetica-Bold",
        22
    )

    c.drawString(
        150,
        760,
        "Diabetes Risk Report"
    )

    c.setFont(
        "Helvetica",
        12
    )

    c.drawString(
        50,
        700,
        f"Patient Name: {name}"
    )

    c.drawString(
        50,
        670,
        f"Prediction: {prediction}"
    )

    c.drawString(
        50,
        640,
        f"Risk Score: {risk:.2f}%"
    )

    c.line(
        50,
        620,
        550,
        620
    )

    c.drawString(
        50,
        590,
        "Health Recommendations"
    )

    if risk < 30:

        recommendation = [
            "Maintain healthy eating habits.",
            "Exercise regularly.",
            "Monitor health annually."
        ]

    elif risk < 70:

        recommendation = [
            "Reduce sugar intake.",
            "Exercise daily.",
            "Monitor blood glucose."
        ]

    else:

        recommendation = [
            "Consult a doctor.",
            "Follow diabetic diet.",
            "Monitor glucose frequently."
        ]

    y = 560

    for item in recommendation:

        c.drawString(
            70,
            y,
            f"• {item}"
        )

        y -= 25

    c.line(
        50,
        430,
        550,
        430
    )

    c.drawString(
        50,
        390,
        "Generated By:"
    )

    c.drawString(
        50,
        360,
        "Diabetes Risk Predictor"
    )

    c.drawString(
        50,
        330,
        "Machine Learning Internship Project"
    )

    c.save()

    return filename